#!/bin/sh

if [ ! `id -u` -eq 0 ] ; then
    echo "
This script requires root priviledges, use sudo.
"
    exit 1
fi

RESP=$(/usr/bin/pen init --config /etc/pen/pen.yaml 2>&1)
case "$RESP" in
    Error*|*'No such file'*)
        echo "
The pen node has returned an error, probably because the pen-clef external signer is enabled, but the node couldn't connect to it.

Fix the configuration and try again.

The node's output was:
        "
        echo "$RESP"
        ;;
    *)
        ETH_ADDRESS=$(echo "$RESP" | grep ethereum | cut -d' ' -f6 | tr -d '"')
        echo "
Please make sure there is sufficient ETH and PEN available on the node's Ethereum address: $ETH_ADDRESS.

Learn how to fund your node by visiting our docs

Once the node's wallet has received the funds it will begin joining the Penguin network.

See the docs for more.
        "
        ;;
esac
